@startuml
entity Projects {
    id
    --
    project_name
}

entity ProjectMembers {
    id
    --
    first_name
    last_name
    email
}

entity Tasks {
    id
    --
    name
}

entity ProjectMemberToProject {
    id
    --
    project_name
    member_name
    task_name
    description
    status
}

Projects ||--o{ ProjectMemberToProject
ProjectMembers ||--o{ ProjectMemberToProject
Tasks ||--o{ ProjectMemberToProject
@enduml